### ISSUE TITLE
Need to add statistics to requirements

### ISSUE THREAD

**Issue by alexblaessle** [mmngreco/IneqPy#9] opened 2019-01-16 13:40 UTC
Hi,

I installed your package using ``python3 setup.py install`` and when importing I got the following traceback:

````
---------------------------------------------------------------------
RuntimeError                        Traceback (most recent call last)
<ipython-input-1-eb6d5708505d> in <module>
----> 1 import ineqpy

/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/_bootstrap.py in _find_and_load(name, import_)

/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/_bootstrap.py in _find_and_load_unlocked(name, import_)

/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/_bootstrap.py in _load_unlocked(spec)

/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/_bootstrap.py in _load_backward_compatible(spec)

/usr/local/lib/python3.7/site-packages/IneqPy-0.2.0+1.g519a71c-py3.7.egg/ineqpy/__init__.py in <module>
      3 '''
      4 
----> 5 from ineqpy.inequality import *
      6 from ineqpy import inequality
      7 from ineqpy.statistics import *

/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/_bootstrap.py in _find_and_load(name, import_)

/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/_bootstrap.py in _find_and_load_unlocked(name, import_)

/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/_bootstrap.py in _load_unlocked(spec)

/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/_bootstrap.py in _load_backward_compatible(spec)

/usr/local/lib/python3.7/site-packages/IneqPy-0.2.0+1.g519a71c-py3.7.egg/ineqpy/inequality.py in <module>
     15 import numpy as np
     16 import pandas as pd
---> 17 from .statistics import mean
     18 from . import utils
     19 

/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/_bootstrap.py in _find_and_load(name, import_)

/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/_bootstrap.py in _find_and_load_unlocked(name, import_)

/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/_bootstrap.py in _load_unlocked(spec)

/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/_bootstrap.py in _load_backward_compatible(spec)

/usr/local/lib/python3.7/site-packages/IneqPy-0.2.0+1.g519a71c-py3.7.egg/ineqpy/statistics.py in <module>
      6 
      7 import pandas as pd
----> 8 from . import _statistics as stat
      9 from . import utils
     10 

/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/_bootstrap.py in _find_and_load(name, import_)

/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/_bootstrap.py in _find_and_load_unlocked(name, import_)

/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/_bootstrap.py in _load_unlocked(spec)

/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/_bootstrap.py in _load_backward_compatible(spec)

/usr/local/lib/python3.7/site-packages/IneqPy-0.2.0+1.g519a71c-py3.7.egg/ineqpy/_statistics.py in <module>
    281 
    282 @guvectorize("float64[:], float64[:], int64, float64[:]", '(n),(n),()->()',
--> 283              nopython=True, cache=True)
    284 def wvar(x, w, kind, out):
    285     """Calculate weighted variance of X.

/usr/local/lib/python3.7/site-packages/numba/npyufunc/decorators.py in wrap(func)
    175 
    176     def wrap(func):
--> 177         guvec = GUVectorize(func, signature, **kws)
    178         for fty in ftylist:
    179             guvec.add(fty)

/usr/local/lib/python3.7/site-packages/numba/npyufunc/decorators.py in __new__(cls, func, signature, **kws)
     48         imp = cls.get_target_implementation(kws)
     49         return imp(func, signature, identity=identity, cache=cache,
---> 50                    targetoptions=kws)
     51 
     52 

/usr/local/lib/python3.7/site-packages/numba/npyufunc/ufuncbuilder.py in __init__(self, py_func, signature, identity, cache, targetoptions)
    271         self.py_func = py_func
    272         self.identity = parse_identity(identity)
--> 273         self.nb_func = jit(target='npyufunc', cache=cache)(py_func)
    274         self.signature = signature
    275         self.sin, self.sout = parse_signature(signature)

/usr/local/lib/python3.7/site-packages/numba/decorators.py in wrapper(func)
    189                           **dispatcher_args)
    190         if cache:
--> 191             disp.enable_caching()
    192         if sigs is not None:
    193             # Register the Dispatcher to the type inference mechanism,

/usr/local/lib/python3.7/site-packages/numba/npyufunc/ufuncbuilder.py in enable_caching(self)
     57 
     58     def enable_caching(self):
---> 59         self.cache = FunctionCache(self.py_func)
     60 
     61     def compile(self, sig, locals={}, **targetoptions):

/usr/local/lib/python3.7/site-packages/numba/caching.py in __init__(self, py_func)
    612     def __init__(self, py_func):
    613         self._name = repr(py_func)
--> 614         self._impl = self._impl_class(py_func)
    615         self._cache_path = self._impl.locator.get_cache_path()
    616         # This may be a bit strict but avoids us maintaining a magic number

/usr/local/lib/python3.7/site-packages/numba/caching.py in __init__(self, py_func)
    347         else:
    348             raise RuntimeError("cannot cache function %r: no locator available "
--> 349                                "for file %r" % (qualname, source_path))
    350         self._locator = locator
    351         # Use filename base name as module name to avoid conflict between

RuntimeError: cannot cache function 'wvar': no locator available for file '/usr/local/lib/python3.7/site-packages/IneqPy-0.2.0+1.g519a71c-py3.7.egg/ineqpy/_statistics.py'
````

Installing statistics via ``pip3 install statistics`` fixed the problem. You probably want to add that to your requirements.txt.

**Comment by mmngreco** [comment] 2019-01-17 08:48
Hi @alexblaessle, Just for clarification you could confirm that the procedure you followed is as follows: 

```
git clone https://github.com/mmngreco/IneqPy.git # this clones the master branch
cd IneqPy
python setup.py install
```

If so, that should be enough and it should work well.

`statistics` is a submodule of IneqPy, the package you have installed is not a dependency, I don't know why it makes ineqpy work but probably the functions that make use of the package have errors.

It seems that the problem is due to numba. However, I just replicated those steps and can't replicate the error.

I recommend you uninstall the statistics package:

```
pip uninstall statistics
```

Could you paste the output of `pip list` ? 

Personally I think the most robust way to do installations is to use pip.
The equivalent way to do it would be:

```
git clone https://github.com/mmngreco/IneqPy.git
cd IneqPy
pip install .
```
or
```
pip install git+https://github.com/mmngreco/IneqPy.git
```

**Comment by mmngreco** [comment] 2019-01-28 09:35
I can reproduce de problem closing issue. If you want update this issue feel free to reopen it.

**Closed by mmngreco** 2019-01-28 09:35 UTC

**Comment by alexblaessle** [comment] 2019-01-28 16:54
Hi, sorry for the delay. Lots of work. I reinstalled it on two different machines (RedHat + OSX brewed) and did not run into the same problem again. This is really weird. But well, it works. Sorry again.

**Comment by mmngreco** [comment] 2019-02-02 16:15
It's ok, good to hear that! ;-)
